from backend.indexing.indexer import Indexer
from backend.retrieval.vector_store import InMemoryVectorStore


class FakeEmbedder:
    def embed_chunks(self, chunks):
        return [
            [1.0, 0.0, 0.0]
            for _ in chunks
        ]


def test_indexer_indexes_records():
    store = InMemoryVectorStore()

    indexer = Indexer(
        embedder=FakeEmbedder(),
        vector_store=store,
    )

    records = [
        {
            "query_id": "q1",
            "query": "What is solar energy?",
            "Answer": "Solar energy comes from the sun.",
            "Eng_Query": "What is solar energy?",
            "Eng_Answer": "Solar energy comes from the sun.",
            "source_lang": "eng_Latn",
            "target_lang": "eng_Latn",
            "query_type": "factoid",
            "passages": {
                "English_passages": [
                    "Solar energy is renewable and comes from sunlight."
                ],
                "Translated_passages": [],
                "is_selected": [1],
            },
            "meta": {},
        }
    ]

    count = indexer.index_records(records)

    assert count == 1

    results = store.search(
        [1.0, 0.0, 0.0],
        top_k=1,
    )
    assert len(results) == 1
    assert results[0][0].chunk_id == "q1:0:0"
    assert results[0][0].text == (
        "Solar energy is renewable and comes from sunlight."
    )
def test_indexer_empty_records():
    store = InMemoryVectorStore()

    indexer = Indexer(
        embedder=FakeEmbedder(),
        vector_store=store,
    )

    count = indexer.index_records([])

    assert count == 0
    assert store.count() == 0


def test_indexer_indexes_multiple_records():
    store = InMemoryVectorStore()

    indexer = Indexer(
        embedder=FakeEmbedder(),
        vector_store=store,
    )

    records = [
        {
            "query_id": "q1",
            "query": "What is solar energy?",
            "Answer": "Solar energy comes from the sun.",
            "Eng_Query": "What is solar energy?",
            "Eng_Answer": "Solar energy comes from the sun.",
            "source_lang": "eng_Latn",
            "target_lang": "eng_Latn",
            "query_type": "factoid",
            "passages": {
                "English_passages": [
                    "Solar energy is renewable and comes from sunlight."
                ],
                "Translated_passages": [],
                "is_selected": [1],
            },
            "meta": {},
        },
        {
            "query_id": "q2",
            "query": "What is wind energy?",
            "Answer": "Wind energy comes from moving air.",
            "Eng_Query": "What is wind energy?",
            "Eng_Answer": "Wind energy comes from moving air.",
            "source_lang": "eng_Latn",
            "target_lang": "eng_Latn",
            "query_type": "factoid",
            "passages": {
                "English_passages": [
                    "Wind energy is generated by moving air."
                ],
                "Translated_passages": [],
                "is_selected": [1],
            },
            "meta": {},
        },
    ]

    count = indexer.index_records(records)

    assert count == 2
    assert store.count() == 2


def test_indexer_preserves_metadata():
    store = InMemoryVectorStore()

    indexer = Indexer(
        embedder=FakeEmbedder(),
        vector_store=store,
    )

    records = [
        {
            "query_id": "q1",
            "query": "What is solar energy?",
            "Answer": "Solar energy comes from the sun.",
            "Eng_Query": "What is solar energy?",
            "Eng_Answer": "Solar energy comes from the sun.",
            "source_lang": "eng_Latn",
            "target_lang": "eng_Latn",
            "query_type": "factoid",
            "passages": {
                "English_passages": [
                    "Solar energy is renewable and comes from sunlight."
                ],
                "Translated_passages": [],
                "is_selected": [1],
            },
            "meta": {
                "source": "test",
                "category": "energy",
            },
        }
    ]

    indexer.index_records(records)

    results = store.search([1.0, 0.0, 0.0], top_k=1)

    result = results[0][0]

    assert result.metadata["source"] == "test"
    assert result.metadata["category"] == "energy"